name: CI

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  # --- Python backend tests ------------------------------------
  backend:
    name: 🐍 Backend (Python) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      # Cache Poetry & pip
      - name: Cache Python deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('backend/poetry.lock') }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Run backend tests
        run: |
          poetry run pytest \
            --maxfail=1 \
            --disable-warnings \
            -q \
            --junitxml=backend-test-results.xml \
            --cov=. \
            --cov-report=xml

      - name: Upload backend test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: backend-test-results.xml

      - name: Upload backend coverage report
        if: always()
        uses: actions/upload
